[package]
name = "stackable-agent"
description = "Tha component of the Stackable Platform that manages installation of services on the workers"
version = "0.1.0-nightly"
authors = ["Sönke Liebau <soenke.liebau@stackable.de>"]
edition = "2018"
license = "Apache-2.0"

[dependencies]
# We are currently referencing the Krustlet directly from a Stackable fork of the official repository.
# The fork is needed to remove the node draining behavior of the Krustlet (see https://github.com/deislabs/krustlet/issues/523)
# There is already a PR for cargo to allow patching of dependencies (see https://github.com/rust-lang/cargo/pull/9001).
kubelet = { git="https://github.com/stackabletech/krustlet.git", rev="1697c48fadd4cfb68a5b6b24c559d9ad3d62dcb2", default-features = true, features= ["derive", "cli"] }
krator = { git="https://github.com/stackabletech/krustlet.git", rev="1697c48fadd4cfb68a5b6b24c559d9ad3d62dcb2"}
oci-distribution = { git="https://github.com/stackabletech/krustlet.git", rev="1697c48fadd4cfb68a5b6b24c559d9ad3d62dcb2"}
k8s-openapi = { version = "0.9", default-features = false, features = ["v1_18"] }
kube = { version= "0.42", default-features = false, features = ["native-tls"] }
kube-derive = "0.43"
anyhow = "1.0"
env_logger = "0.8"
async-trait = "0.1"
tokio = { version = "0.2.24", features = ["fs", "stream", "macros", "io-util", "sync", "signal", "uds"] }
log = "0.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
reqwest = "0.10"
flate2 = "1.0"
tar = "0.4"
handlebars = "3.5"
thiserror = "1.0"
url = "2.2"
stackable_config = { git = "https://github.com/stackabletech/common.git", branch = "main" }
phf = { version = "0.7.24", features = ["macros"] }
dbus = "0.9.2"
hostname = "0.3"
shellexpand = "2.1"
regex = "1"
nix = "0.20"
lazy_static = "1"
strum = { version = "0.20", features = ["derive"] }
strum_macros = "0.20"

[dev-dependencies]
indoc = "1.0"
rstest = "0.6"
serde_yaml = "0.8"

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1

[package.metadata.deb]
maintainer-scripts = "packaging/debian/"
systemd-units = { enable = false }
assets = [
    ["packaging/config/agent.conf", "etc/stackable-agent/", "644"],
    ["target/release/agent", "opt/stackable-agent/stackable-agent", "755"],
]
