[package]
name = "stackable-agent"
version = "0.1.0"
authors = ["Sönke Liebau <soenke.liebau@stackable.de>"]
edition = "2018"

[dependencies]
# We are currently referencing the Krustlet directly from the repository, because some features that we are using have
# (exponential backoff most prominently) have not yet been included in a release
# We will look to move this to officially released versions as soon as possible
kubelet = { git="https://github.com/deislabs/krustlet.git", rev="ac218b38ba564de806568e49d9e38aaef9f41537", default-features = true, features= ["derive", "cli"] }
oci-distribution = { git="https://github.com/deislabs/krustlet.git", rev="ac218b38ba564de806568e49d9e38aaef9f41537"}
k8s-openapi = { version = "0.9", default-features = false, features = ["v1_18"] }
kube = { version= "0.42", default-features = false, features = ["native-tls"] }
kube-derive = "0.43"
anyhow = "1.0"
env_logger = "0.7"
async-trait = "0.1"
tokio = { version = "0.2.22", features = ["fs", "stream", "macros", "io-util", "sync", "signal", "uds"] }
log = "0.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
reqwest = "0.10"
flate2 = "1.0"
tar = "0.4"
handlebars = "3.5"
thiserror = "1.0"
url = "2.2"
pnet = "0.27"
stackable_config = { git = "https://github.com/stackabletech/common.git", branch = "main" }
phf = { version = "0.7.24", features = ["macros"] }
dbus = "0.9.0"
hostname = "0.3"
shellexpand = "2.1"

[dev-dependencies]
indoc = "1.0"
rstest = "0.6"
serde_yaml = "0.8"

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
