


=== tag

*Default value*: No default value

*Required*: false

*Multiple values:* true


A "key=value" pair that should be assigned to this agent as tag. This can be specified multiple times to assign additional tags.

Tags are the main way of identifying nodes to assign services to later on.


=== server-key-file

*Default value*: No default value

*Required*: false

*Multiple values:* false


Private key file (in PKCS8 format) to use for the local webserver the Krustlet starts.


=== log-directory

*Default value*: /opt/stackable/logs

*Required*: false

*Multiple values:* false


This directory will serve as starting point for all log files which this service creates.
Every service will get its own subdirectory created within this directory.
Anything that is then specified in the log4j config or similar files will be resolved relatively to this directory.

The agent will need full access to this directory and tries to create it if it does not exist.


=== hostname

*Default value*: No default value

*Required*: false

*Multiple values:* false


The hostname to register the node under in Kubernetes - defaults to system hostname.


=== server-cert-file

*Default value*: No default value

*Required*: false

*Multiple values:* false


The certificate file for the local webserver which the Krustlet starts.


=== no-config

*Default value*: No default value

*Required*: false

*Multiple values:* false


If this option is specified, any file referenced in AGENT_CONF environment variable will be ignored.


=== bootstrap-file

*Default value*: /etc/kubernetes/bootstrap-kubelet.conf

*Required*: false

*Multiple values:* false


The bootstrap file to use in case Kubernetes bootstraping is used to add the agent.


=== server-bind-ip

*Default value*: No default value

*Required*: false

*Multiple values:* false


The local IP to register as the node's ip with the apiserver. Will be automatically set to the first address of the first non-loopback interface if not specified.


=== data-directory

*Default value*: /var/stackable/agent/data

*Required*: false

*Multiple values:* false


The directory where the stackable agent should keep its working data.


=== config-directory

*Default value*: /opt/stackable/config

*Required*: false

*Multiple values:* false


This directory will serve as starting point for all log files which this service creates.

Every service will get its own subdirectories created within this directory - for every service start a
new subdirectory will be created to show a full history of configuration that was used for this service.

ConfigMaps which are specified in the pod that describes this service will be created relative to these run
directories - unless the mounts specify an absolute path, in which case it is allowed to break out of this directory.

WARNING: This allows anybody who can specify pods more or less full access to the file system on the machine running the agent!

The agent will need full access to this directory and tries to create it if it does not exist.


=== server-port

*Default value*: 3000

*Required*: false

*Multiple values:* false


Port to listen on for callbacks.


=== package-directory

*Default value*: /opt/stackable/packages

*Required*: false

*Multiple values:* false


This directory will serve as starting point for packages that are needed by pods assigned to this node.\n Packages will be downloaded into the "_download" folder at the top level of this folder as archives and remain there for potential future use.

Archives will the be extracted directly into this folder in subdirectories following the naming
scheme of "productname-productversion".

The agent will need full access to this directory and tries to create it if it does not exist.